---
repos:
  - repo: https://github.com/awslabs/git-secrets
    # Must be post the 1.3.0 release
    rev: 5357e18bc27b42a827b6780564ea873a72ca1f01
    hooks:
      - id: git-secrets
        entry: git-secrets --scan
        files: .
        args: [--untracked]

  # Check shell scripts example
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: [-l, -i, '2', -ci, -sr, -w]
      - id: shellcheck

  # Run these last since they make broad changes to whitespace, etc.
  # and might be required to fix files that were touched by
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Git style
      - id: check-added-large-files
        args: [--maxkb=2200]
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      # - id: no-commit-to-branch
      # Common errors
      - id: end-of-file-fixer
        exclude: (\.asc)$
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-executables-have-shebangs
      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

      # Security
      - id: detect-private-key
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint-config.yaml]
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.16.0
    hooks:
      - id: yamlfix
